// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE3qku_T_JCmT39WDkjcK2C8BHL2-HLoA',
    appId: '1:590043477972:web:8124b63d615690f874c841',
    messagingSenderId: '590043477972',
    projectId: 'parkingmapguedalia',
    authDomain: 'parkingmapguedalia.firebaseapp.com',
    storageBucket: 'parkingmapguedalia.appspot.com',
    measurementId: 'G-T34Z7E7ER8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxkMYd5Qs5eCCo8K0AhV4g2us4VP4k9CU',
    appId: '1:590043477972:android:91c912d18ceca61e74c841',
    messagingSenderId: '590043477972',
    projectId: 'parkingmapguedalia',
    storageBucket: 'parkingmapguedalia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6onwYaudwXd7P4pgVOuxmuo0pVbWYBSk',
    appId: '1:590043477972:ios:d16e527ebeca93d574c841',
    messagingSenderId: '590043477972',
    projectId: 'parkingmapguedalia',
    storageBucket: 'parkingmapguedalia.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6onwYaudwXd7P4pgVOuxmuo0pVbWYBSk',
    appId: '1:590043477972:ios:d16e527ebeca93d574c841',
    messagingSenderId: '590043477972',
    projectId: 'parkingmapguedalia',
    storageBucket: 'parkingmapguedalia.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE3qku_T_JCmT39WDkjcK2C8BHL2-HLoA',
    appId: '1:590043477972:web:b30f46044314450974c841',
    messagingSenderId: '590043477972',
    projectId: 'parkingmapguedalia',
    authDomain: 'parkingmapguedalia.firebaseapp.com',
    storageBucket: 'parkingmapguedalia.appspot.com',
    measurementId: 'G-G2PK6ZTV8Z',
  );
}
